trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      py37:
        python.version: '3.7'
        onnx_ml: 0
        onnx_verify_proto: 0
      py36:
        python.version: '3.6'
        onnx_ml: 0
        onnx_verify_proto: 0
      py37_onnx_ml:
        python.version: '3.7'
        onnx_ml: 1
        onnx_verify_proto: 0
      py36_verify_proto:
        python.version: '3.6'
        onnx_ml: 0
        onnx_verify_proto: 1
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
      python -m pip install --upgrade pip
      python -m pip install --quiet pytest==5.4.3 nbval numpy
      
      set ONNX_DIR=%cd%
      cd ..
      git clone https://github.com/protocolbuffers/protobuf.git
      cd protobuf
      set PROTO_INSTALL_DIR=%cd%\install
      git checkout 3.12.x
      cd cmake
      cmake -Dprotobuf_MSVC_STATIC_RUNTIME=OFF -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_BUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=%PROTO_INSTALL_DIR%
      msbuild protobuf.sln /m /p:Configuration=Release
      msbuild INSTALL.vcxproj /p:Configuration=Release      
      cd ONNX_DIR
      set PATH=%PROTO_INSTALL_DIR%\bin;%PATH%
      
      git submodule update --init --recursive
      set ONNX_BUILD_TESTS=1
      set ONNX_ML=$(onnx_ml)
      set ONNX_VERIFY_PROTO_3=$(onnx_verify_proto)
      set USE_MSVC_STATIC_RUNTIME=0
      set CMAKE_ARGS=-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF -DProtobuf_USE_STATIC_LIBS=ON -DONNX_USE_LITE_PROTO=ON -DONNX_WERROR=ON

      python setup.py --quiet install
      pytest
      IF NOT %ERRORLEVEL% EQU 0 (
        @echo "pytest failed"
        EXIT 1
      )

      python onnx/defs/gen_doc.py
      python onnx/gen_proto.py -l
      python onnx/gen_proto.py -l --ml

      rm -rf .setuptools-cmake-build
      pip install --quiet -e .[mypy]
      python setup.py typecheck

      git diff --exit-code  -- . :(exclude)onnx/onnx-data.proto :(exclude)onnx/onnx-data.proto3
      IF NOT %ERRORLEVEL% EQU 0 (
        @echo "git diff returned failures"
        EXIT 1
      )      
    displayName: Install and test ONNX
