name: MacRelease

on:
  push:
    branches:
      - rel-*
  # test this PR for now, remove it before the merge
  pull_request:
    branches: [ master ]
env:
  MACOSX_DEPLOYMENT_TARGET: 10.12
jobs:
  build:
    runs-on: macos-10.15
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        architecture: ['x64']
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}


    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Conda info
      shell: bash -l {0}
      run: conda info
    - name: Conda list
      shell: pwsh
      run: conda list
    - name: Install python dependencies
      run: |
        conda install protobuf==3.11.3 pytest==5.4.3 numpy wheel setuptools
        python -m pip install --upgrade pip
        pip install nbval
    - name: Build wheel
      env:
        ONNX_BUILD_TESTS: 1
        USE_MSVC_STATIC_RUNTIME: 1
        ONNX_ML: 1
        CMAKE_ARGS: "-DONNX_USE_LITE_PROTO=ON -DONNXIFI_DUMMY_BACKEND=ON -DONNX_WERROR=ON"
      run: |
        python setup.py bdist_wheel
        # Get-ChildItem -Path dist/*.whl | foreach {pip install --upgrade $_.fullname}
        pip install dist/*.whl
        pytest
        # upload to PyPI automatically
    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: dist
