name: MacRelease

on:
  push:
    branches: [ master, rel-*]
  # test this PR for now, remove it before the merge
  pull_request:
    branches: [ master ]

env:
  MACOSX_DEPLOYMENT_TARGET: 10.12

jobs:
  build:
    runs-on: macos-10.15
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
        architecture: ['x86_64']

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Install Python dependencies
      run: |
        python -m pip install -q --upgrade pip
        python -m pip install -q numpy setuptools wheel

    - name: Install protobuf dependencies
      run: |
        # Install protobuf 3.11.3
        brew update
        brew install autoconf && brew install automake
        cd ..
        wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.3/protobuf-cpp-3.11.3.tar.gz
        tar -xvf protobuf-cpp-3.11.3.tar.gz
        cd protobuf-3.11.3
        ./autogen.sh
        ./configure --disable-shared
        make
        make check
        make install
        cd ../onnx

    - name: Build wheel and install
      env:
        CC: "clang"
        CXX: "clang++"
        ONNX_ML: 1
        CMAKE_ARGS: "-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF -DProtobuf_USE_STATIC_LIBS=ON -DONNX_USE_LITE_PROTO=ON"
      run: |
        # Currently GitHub Action agent is using 10.14 Python, use -p to force change the final MACOSX_DEPLOYMENT_TARGET
        # Change -p if MACOSX_DEPLOYMENT_TARGET is different
        python setup.py bdist_wheel -p macosx_10_12_x86_64
        for file in dist/*.whl; do python -m pip install --upgrade $file; done

    - name: Test the installed wheel
      run: |
        python -m pip install -q pytest==5.4.3 nbval
        pytest

    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: dist
