# Weekly ci workflow for model zoo.
# Runs model checker for all models

name: Weekly CI with latest onnx.checker

# Triggers the workflow on push or pull request events but only for the master branch
on:
  # test this PR for now, remove it before the merge
  pull_request:
    branches: [ master ]  
  schedule:
    # run weekly on Sunday 23:59
    - cron:  '59 23 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        architecture: ['x64']

    steps:
    - uses: actions/checkout@v2
      name: Checkout repo
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest==5.4.3 nbval numpy wheel
        python -m pip install virtualenv
        python -m virtualenv py$(python.version)
        source py$(python.version)/bin/activate
        python -m pip install numpy protobuf
        sudo apt-get install protobuf-compiler libprotoc-dev
    - name: Install latest ONNX and dependencies
      run: |
        $Env:ONNX_BUILD_TESTS=1
        $Env:USE_MSVC_STATIC_RUNTIME=1
        $Env:ONNX_ML=1
        $Env:CMAKE_ARGS="-DONNX_USE_LITE_PROTO=ON"
        python setup.py --quiet install
    - name: Test all models with onnx.checker and onnx.shape_inference
      run: |
        cd ..
        git clone https://github.com/onnx/models.git
        cd models
        python ../onnx/workflow_scripts/test_model_zoo.py

    