# Weekly ci workflow for model zoo.
# Runs model checker for all models

name: Weekly CI with latest onnx.checker

# Triggers the workflow on push or pull request events but only for the master branch
on:
  # test this PR for now, remove it before the merge
  pull_request:
    branches: [ master ]  
  schedule:
    # run weekly on Sunday 23:59
    - cron:  '59 23 * * SUN'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7]
        architecture: ['x64']
        onnx-version: ['1.7']

    steps:
      - uses: actions/checkout@v2
        name: Checkout repo

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
    - name: Install vcpkg dependencies
      run: vcpkg install protobuf:${{ matrix.architecture }}-windows-static
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        # pytest 6.0 made deprecation warnings fail by default, pinning pytest to 5.4.3.
        # TODO replace deprecated function with the suggested one. https://docs.pytest.org/en/stable/deprecations.html#id5
        pip install pytest==5.4.3 nbval numpy wheel
    - name: Install latest ONNX and dependencies
      run: |
        $Env:USE_MSVC_STATIC_RUNTIME=1
        $Env:ONNX_ML=1
        $Env:CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF -DProtobuf_USE_STATIC_LIBS=ON -DONNX_USE_LITE_PROTO=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ matrix.architecture }}-windows-static"
        python setup.py --quiet install

    